FEE_FEATURE_CARD = 'card'
FEE_FEATURE_BUSINESS_ACCOUNT = 'business_account'
FEE_FEATURE_ONLINE_PAYMENT = 'online_payment'
FEE_FEATURE_SUBSCRIPTION = 'subscription'


FEE_FEATURE_CHOICES = (
    (FEE_FEATURE_CARD, FEE_FEATURE_CARD),
    (FEE_FEATURE_BUSINESS_ACCOUNT, FEE_FEATURE_BUSINESS_ACCOUNT),
    (FEE_FEATURE_ONLINE_PAYMENT, FEE_FEATURE_ONLINE_PAYMENT),
    (FEE_FEATURE_SUBSCRIPTION, FEE_FEATURE_SUBSCRIPTION)
)
